exports.licenses = [
  {'short': 'CC-BY',
   'url': 'http://creativecommons.org/licenses/by/2.5/dk/',
   'img': 'http://i.creativecommons.org/l/by/2.5/88x31.png'},
  {'short': 'CC-BY-NC',
   'url': 'http://creativecommons.org/licenses/by-nc/2.5/dk/',
   'img': 'http://i.creativecommons.org/l/by-nc/2.5/88x31.png'},
  {'short': 'CC-BY-NC-ND',
   'url': 'http://creativecommons.org/licenses/by-nc-nd/2.5/dk/',
   'img': 'http://i.creativecommons.org/l/by-nc-nd/2.5/88x31.png'},
  {'short': 'CC-BY-NC-SA',
   'url': 'http://creativecommons.org/licenses/by-nc-sa/2.5/dk/',
   'img': 'http://i.creativecommons.org/l/by-nc-sa/2.5/88x31.png'},
  {'short': 'CC-BY-ND',
   'url': 'http://creativecommons.org/licenses/by-nd/2.5/dk/',
   'img': 'http://i.creativecommons.org/l/by-nd/2.5/88x31.png'},
  {'short': 'CC-BY-SA',
   'url': 'http://creativecommons.org/licenses/by-sa/2.5/dk/',
   'img': 'http://i.creativecommons.org/l/by-sa/2.5/88x31.png'},
  null,
  null,
  null
];
